### ISSUE TITLE
这个该如何自定义呢？

### ISSUE THREAD

**Issue by IoriMaboroshi** [songquanpeng/microblog#1]

**Comment by songquanpeng** [comment]
改这里的布局和样式：
1. https://github.com/songquanpeng/microblog/blob/master/public/index.html
2. https://github.com/songquanpeng/microblog/blob/master/public/static/app.css

**Comment by songquanpeng** [comment]
可以去这里看一下别人的样式，拿来~抄一下~借鉴一下：https://github.com/daibor/nonsense.fun#%E4%B8%80%E4%BA%9B%E4%BD%9C%E5%93%81

**Comment by IoriMaboroshi** [comment]
！回复好快，谢谢大佬w

**Comment by songquanpeng** [comment]
~~我住在 GitHub 的，不是~~

**Comment by IoriMaboroshi** [comment]
草www
看了之后觉得直接去整个废话胶囊好了（x

**Comment by IoriMaboroshi** [comment]
咱就是想整个碎碎念的（x

**Comment by songquanpeng** [comment]
我这个如果有自己的服务器的话会更好一些，我记得他那个需要 LeanCloud，发帖不是很方便。

**Comment by IoriMaboroshi** [comment]
主要咱是小白（x
~go语言还要在编译一边（x~

**Comment by songquanpeng** [comment]
我有编译好的：https://github.com/songquanpeng/microblog/releases

**Comment by IoriMaboroshi** [comment]
但是更改完样式什么的还要再编译（x

**Comment by songquanpeng** [comment]
用在线 IDE 编译就好了：https://gitpod.io/#https://github.com/songquanpeng/microblog

或者用 GitHub 提供的 Codespace

这些都是不用自己配置环境的，也可以在线预览。

当然，只是建议哈，废话胶囊那个也挺好的。

**Comment by IoriMaboroshi** [comment]
嗯嗯ww
谢谢大佬

**Comment by songquanpeng** [comment]
另外，你修改好之后，只需要打个 tag，GItHub Actions 也会自动编译并发布。

**Comment by IoriMaboroshi** [comment]
~咱现在连css都还没玩懂，只有html还能用用~

**Comment by songquanpeng** [comment]
多写写就好了~

**Comment by IoriMaboroshi** [comment]
![22-12-05-160811](https://user-images.githubusercontent.com/117876175/205585780-5827212b-7b46-473b-9708-d09384d62fc9.png)
服务器~不理我~死机了草

**Comment by songquanpeng** [comment]
有概率被墙了

**Comment by IoriMaboroshi** [comment]
是死机了（x
~梯子是24h不关的~

**Comment by songquanpeng** [comment]
这样，我还没遇到过服务器本身挂掉的情况 2333

**Comment by IoriMaboroshi** [comment]
咱服务器拉跨（
